### ISSUE TITLE
upos for manche

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_German-HDT#8]
I noticed "manche" with xpos `PIAT` has upos `DET` in HDT, but upos `PRON` in GSD. Should this be unified?

**Comment by dan-zeman** [comment]
I think `DET` is correct. And since this issue is about language-specific guidelines rather than a treebank-specific bug, it probably belongs to the docs repo?

Related: https://github.com/UniversalDependencies/docs/issues/786

**Comment by dan-zeman** [comment]
Fixed in https://github.com/UniversalDependencies/UD_German-GSD/commit/f43dd743c0fd0350e12097055d57a90b6278b161
